services:
  - name: "devops-ui"
    git_repo: "https://github.com/ruos-sovanra/devops-ui.git"
    git_branch: "main"

  - name: "spring-ops"
    git_repo: "https://github.com/ruos-sovanra/spring-ops.git"
    git_branch: "main"

  - name: "spring-api"
    git_repo: "https://github.com/ruos-sovanra/fast-api.git"
    git_branch: "main"
